name: Pull Request Pipeline

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Run tests
        run: uvx --with-requirements requirements.txt pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Analyze Formatting
        run: uvx ruff check
