API_TITLE: str = "Tallee Match-Sharing Relay"
API_SUMMARY: str = "Relay for Tallee match data"
API_VERSION: str = "0.0.1"
API_REQUEST_MAX_PAYLOAD_BYTES: int = 256 * 1024
TALLEE_SHARE_TOKEN_LETTERS: str = "ABCDEFGHJKMNPQRSTUVWXYZ"
TALLEE_SHARE_TOKEN_NUMBERS: str = "23456789"
TALLEE_SHARE_TOKEN_ALPHABET: str = TALLEE_SHARE_TOKEN_LETTERS + TALLEE_SHARE_TOKEN_NUMBERS
TALLEE_SHARE_TOKEN_LENGTH: int = 6